Aktivnost za dan 2024-05-10 - 2021240408
jovansimonovic/isa.be pull request #1
Opened 2024-05-12 15:21 UTC by jovansimonovic

2024-05-12 17:23 UTC, pbisevac requested changes
Can you add some validation for User Model? @jovansimonovic

2024-05-12 17:25 UTC, pbisevac requested changes

2024-05-12 17:25 UTC, pbisevac commented on src/main/java/com/example/demo/models/UserModel.java
> +  private String email;
Add some validation od fields

2024-05-13 09:09 UTC, jovansimonovic commented on src/main/java/com/example/demo/models/UserModel.java
> +  private String email;
Added validation for firstName, lastName and email. Added failure message for invalid user registration attempts (server returns "Neuspesno registrovan")

2024-05-13 11:07 UTC, pbisevac approved these changes
Well done, you can merge

2024-05-14 13:48 UTC, merged